workflows:
  ios-sim:
    name: Build iOS Simulator
    environment:
      flutter: stable
      xcode: latest
    triggering:
      events:
        - push
        - pull_request
    scripts:
      # 1)Install CocoaPods
      - name: Install pods
        script: |
          cd ios
          pod install --repo-update
          cd ..

      # 2)Fetch dependencies & build untuk Simulator
      - name: Build for Simulator
        script: |
          flutter clean
          flutter pub get
          flutter build ios --simulator --no-codesign

      # 3)Zip .app
      - name: Zip .app
        script: |
          # output .app biasanya di build/ios/iphonesimulator/Runner.app
          ZIP_PATH="$PWD/RunnerSimulator.zip"
          APP_PATH="$PWD/build/ios/iphonesimulator/Runner.app"
          if [ ! -d "$APP_PATH" ]; then
            echo "Error: $APP_PATH not found"
            exit 1
          fi
          zip -qr "$ZIP_PATH" "$APP_PATH"
          echo "Zipped to $ZIP_PATH"

    artifacts:
      # pastikan path ini sesuai lokasi ZIP_PATH di atas
      - RunnerSimulator.zip
