name: hbo_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.6.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+10
  camera: ^0.11.1
  tflite_flutter: ^0.11.0
  image: ^3.2.0 # Tambahkan ini untuk package image
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  assets:
    - assets/
    - assets/Cattleya/intermedia/
    - assets/Cattleya/labiatacoerulea/
    - assets/Cattleya/walkeriana/
    - assets/Dendrobium/aphylum/
    - assets/Dendrobium/macrophylum/
    - assets/Dendrobium/spectabile/
    - assets/Oncidium/brassia/
    - assets/Oncidium/goldenshower/
    - assets/Oncidium/miltonia/
    - assets/Phalaenopsis/amabilis/
    - assets/Phalaenopsis/belina/
    - assets/Phalaenopsis/gigantea/
    - assets/Phalaenopsis/belina/
    - assets/Vanda/sanderiana/
    - assets/Vanda/teres/
    - assets/Vanda/tricolor/
    - assets/labels.txt
    - assets/model.tflite

  uses-material-design: true

