name: Build iOS Simulator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-simulator:
    runs-on: macos-13

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter 3.27.4
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.4'
          architecture: x64

      - name: Install dependencies
        run: |
          flutter --version
          flutter pub get

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install
          cd ..

      - name: Build for iOS Simulator
        run: |
          flutter clean
          flutter build ios --simulator

      - name: Check Runner.app exists
        run: ls -R build/ios/iphonesimulator

      - name: Upload Runner.app
        uses: actions/upload-artifact@v4
        with:
          name: Runner.app
          path: build/ios/iphonesimulator/Runner.app
